/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mephi.summerexam;

import java.awt.Color;
import javax.swing.JButton;
import org.apache.commons.lang3.ArrayUtils;

/**
 *
 * @author mrsot
 */
public class JFrame_main extends javax.swing.JFrame {
    private JButton previousButton1;
    private JButton previousButton2;
    private JButton currentButton1;
    private JButton currentButton2;
    private Executor executor = new Executor();
    private JButton[] jbuttons;
    private JButton[] jbuttonsFromMsc;
    private JButton[] jbuttonsFromSPb;
    private Ship ship1;
    private Ship ship2;
    private int cyclesHere1 = 0;
    private int cyclesHere2 = 0;
    
    /**
     * Creates new form JFrame_main
     */
    public JFrame_main() {
        initComponents();
        jButton_nextReservoir.setEnabled(false);
        this.jbuttonsFromSPb = new JButton[]{jButton1, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9, jButton10, jButton11, jButton12, jButton13, jButton14, jButton15, jButton16, jButton17, jButton18, jButton19};
        for (JButton jbutton : jbuttonsFromSPb) {
            jbutton.setBackground(Color.YELLOW);
            //jbutton.setText("<html><body bgcolor = red>" + jbutton.getText() + "</body></html>");
            //jbutton.setEnabled(false);
        }
        jbuttonsFromMsc = jbuttonsFromSPb.clone();
        ArrayUtils.reverse(jbuttonsFromMsc);
        ship1 = new Ship(false);
        ship2 = new Ship(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel_SPb = new javax.swing.JLabel();
        jLabel_MSC = new javax.swing.JLabel();
        jLabel_clock_text = new javax.swing.JLabel();
        jButton_nextClockCycle = new javax.swing.JButton();
        jButton_restart = new javax.swing.JButton();
        jLabel_clockCycle = new javax.swing.JLabel();
        jComboBox_mode = new javax.swing.JComboBox<>();
        jLabel_mode = new javax.swing.JLabel();
        jButton_nextReservoir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Channel 52");

        jButton2.setText("Sluice 1");

        jButton3.setText("Channel 53");

        jButton4.setText("Ship's passage 54");

        jButton5.setText("Channel 55");

        jButton6.setText("Sluice 2");

        jButton7.setText("Channel 56");

        jButton8.setText("Ship's passage 57");

        jButton9.setText("Channel 58");

        jButton10.setText("Sluice 3");

        jButton11.setText("Channel 59");

        jButton12.setText("Sluice 4");

        jButton13.setText("Channel 60");

        jButton14.setText("Sluice 5");

        jButton15.setText("Channel 61");

        jButton16.setText("Ship's passage 62");

        jButton17.setText("Channel 63");

        jButton18.setText("Sluice 6");

        jButton19.setText("Channel 64");

        jLabel_SPb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_SPb.setText("Saint-Petersburg");

        jLabel_MSC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_MSC.setText("Moscow");

        jLabel_clock_text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_clock_text.setText("Current clock cycle: ");

        jButton_nextClockCycle.setText("Next clock cycle");
        jButton_nextClockCycle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextClockCycleActionPerformed(evt);
            }
        });

        jButton_restart.setText("Restart");
        jButton_restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_restartActionPerformed(evt);
            }
        });

        jLabel_clockCycle.setText("0");

        jComboBox_mode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Multiple" }));
        jComboBox_mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_modeActionPerformed(evt);
            }
        });

        jLabel_mode.setText("Clock cycles by click");

        jButton_nextReservoir.setText("Next reservoir");
        jButton_nextReservoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextReservoirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel_SPb))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_mode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel_mode)
                                .addGap(152, 152, 152)
                                .addComponent(jLabel_clock_text)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_clockCycle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton_nextClockCycle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_nextReservoir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_restart, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(193, 193, 193))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel_MSC)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SPb)
                    .addComponent(jLabel_clock_text)
                    .addComponent(jLabel_clockCycle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_mode))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_MSC)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_mode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jButton_nextReservoir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_nextClockCycle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_restart)))))
                .addContainerGap(563, Short.MAX_VALUE))
        );

        jScrollPane.setViewportView(jPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1067, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_nextClockCycleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextClockCycleActionPerformed
        if ("0".equals(jLabel_clockCycle.getText())) {
            nextButton(1);
        }
        if ("20".equals(jLabel_clockCycle.getText())) {
            nextButton(2);
        }
        refreshClockCycleLabel(1);
        if (currentButton1 != null && ! executor.check(currentButton1, ship1)) {
            nextButton(1);
        }
        if (currentButton2 != null && ship2 != null && ! executor.check(currentButton2, ship2)) {
            nextButton(2);
        }
    }//GEN-LAST:event_jButton_nextClockCycleActionPerformed

    private void jButton_restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_restartActionPerformed
        jLabel_clockCycle.setText("0");
        if(currentButton1 != null){currentButton1.setBackground(Color.YELLOW);}
        if(currentButton2 != null){currentButton2.setBackground(Color.YELLOW);}
        previousButton1 = null;
        previousButton2 = null;
        currentButton1 = null;
        currentButton2 = null;
        executor.getPassedSluices().clear();
        jComboBox_modeActionPerformed(evt);
    }//GEN-LAST:event_jButton_restartActionPerformed

    private void jComboBox_modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_modeActionPerformed
        if (jComboBox_mode.getSelectedIndex() == 0) {
            jButton_nextReservoir.setEnabled(false);
            jButton_nextClockCycle.setEnabled(true);
        } else {
            jButton_nextReservoir.setEnabled(true);
            jButton_nextClockCycle.setEnabled(false);
        }
        if (currentButton1 == null & previousButton1 != null & currentButton2 == null & previousButton2 != null) {
            jButton_nextReservoir.setEnabled(false);
            jButton_nextClockCycle.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox_modeActionPerformed

    private void jButton_nextReservoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextReservoirActionPerformed
        if ("0".equals(jLabel_clockCycle.getText())) {
            nextButton(1);
            refreshClockCycleLabel(1);
            //cyclesHere1 += 1;
            return;
        }
        if ("20".equals(jLabel_clockCycle.getText())) {
            nextButton(2);
            //cyclesHere2 += 1;
            cyclesHere1 = 0;
            if (!executor.check(currentButton1, ship1)) {
                nextButton(1);
                //cyclesHere1 = 0;
            } else {
                //cyclesHere1 += 1;
                executor.decrementClockCycleHere1();
            }
            refreshClockCycleLabel(1);
            return;
        }
        if (currentButton2 == null) {
            while (executor.check(currentButton1, ship1)) {
                //System.out.println(Integer.parseInt(jLabel_clockCycle.getText()) + cyclesHere1);
                if (Integer.parseInt(jLabel_clockCycle.getText()) + cyclesHere1 == 20) {
                    refreshClockCycleLabel(cyclesHere1);
                    break;
                }
                cyclesHere1 += 1;
            }
            //refreshClockCycleLabel(cyclesHere1);
        } else if (currentButton1 == null) {
            while (executor.check(currentButton2, ship2)) {
                cyclesHere2 += 1;
            }
            //refreshClockCycleLabel(cyclesHere2);
        } else {
            while (executor.check(currentButton1, ship1) & executor.check(currentButton2, ship2)) {
                cyclesHere1 += 1;
                cyclesHere2 += 1;
            }
        }
        //refreshClockCycleLabel(cyclesHere);
        boolean temp = true;
        if (currentButton1 != null & executor.getClockCycleHere1() == 0) {
            refreshClockCycleLabel(cyclesHere1);
            nextButton(1);
            temp = false;
            cyclesHere2 = 0;
            cyclesHere1 = 0;
        }
        if (currentButton2 != null & executor.getClockCycleHere2() == 0) {
            if(temp){refreshClockCycleLabel(cyclesHere2);}
            nextButton(2);
            cyclesHere2 = 0;
            cyclesHere1 = 0;
        }
    }//GEN-LAST:event_jButton_nextReservoirActionPerformed

    public void refreshClockCycleLabel(int cycles){
        int n = Integer.parseInt(jLabel_clockCycle.getText()) + cycles;
        jLabel_clockCycle.setText(String.valueOf(n));
    }
    
    public void nextButton(int ship){
        switch (ship) {
            case 1:
                if (currentButton1 == null) {
                    currentButton1 = jbuttonsFromMsc[0];
                    currentButton1.setBackground(Color.red);
                } else {
                    previousButton1 = currentButton1;
                    if (currentButton1 != jbuttonsFromMsc[jbuttonsFromMsc.length - 1]) {
                        currentButton1 = jbuttonsFromMsc[ArrayUtils.indexOf(jbuttonsFromMsc, previousButton1) + 1];
                        currentButton1.setBackground(Color.red);
                    } else {
                        if (currentButton2 == null) {
                            jButton_nextClockCycle.setEnabled(false);
                            jButton_nextReservoir.setEnabled(false);
                        }
                        currentButton1 = null;
                    }
                    if (previousButton1 != currentButton2) {
                        previousButton1.setBackground(Color.YELLOW);
                    } else {
                        previousButton1.setBackground(Color.red);
                    }
                }
                break;
            case 2:
                if (currentButton2 == null) {
                    currentButton2 = jbuttonsFromSPb[0];
                    currentButton2.setBackground(Color.red);
                } else {
                    previousButton2 = currentButton2;
                    if (currentButton2 != jbuttonsFromSPb[jbuttonsFromSPb.length - 1]) {
                        currentButton2 = jbuttonsFromSPb[ArrayUtils.indexOf(jbuttonsFromSPb, previousButton2) + 1];
                        currentButton2.setBackground(Color.red);
                    } else {
                        if (currentButton1 == null) {
                            jButton_nextClockCycle.setEnabled(false);
                            jButton_nextReservoir.setEnabled(false);
                        }
                        currentButton2 = null;
                    }
                    if (previousButton2 != currentButton1) {
                        previousButton2.setBackground(Color.YELLOW);
                    } else {
                        previousButton2.setBackground(Color.red);
                    }
                }
                break;
            default:
                System.err.println("Such ship doesn't exist!");
        }
        if (currentButton1 == currentButton2 & currentButton1 != null) {
            currentButton1.setBackground(Color.MAGENTA);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_nextClockCycle;
    private javax.swing.JButton jButton_nextReservoir;
    private javax.swing.JButton jButton_restart;
    private javax.swing.JComboBox<String> jComboBox_mode;
    private javax.swing.JLabel jLabel_MSC;
    private javax.swing.JLabel jLabel_SPb;
    private javax.swing.JLabel jLabel_clockCycle;
    private javax.swing.JLabel jLabel_clock_text;
    private javax.swing.JLabel jLabel_mode;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
